[workspace]
members = [
    "lib",
    "c",
    "repl",
]
resolver = "2"

[workspace.package]
version = "0.2.5"
edition = "2021"

[workspace.dependencies]
hyperon = { path = "./lib", version = "0.2.3" }
hyperon-atom = { path = "./hyperon-atom" }
regex = "1.11.0"
log = "0.4.0"
env_logger = "0.8.4"

[profile.release]
strip = "symbols"
