[package]
name = "das"
version = "0.0.1"
edition.workspace = true

[dependencies]
# hyperon = { version = "0.2.2" }
tonic = "0.12.3"
tokio = {version = "1.43.0", features = ["full"]}
prost = "0.13.5"
log.workspace = true

[build-dependencies]
tonic-build = "*"
